"""全局配置常量：曲线名规范化映射与单位换算系数。"""

# 原始曲线名 → 规范化曲线名
RAW_DATA_NAME_SWITCH_MAP = {
    "DEPTH(m)": "DEPTH",
    "DEPTH(M)": "DEPTH",
    "GR(GAPI)": "GR",
    "GR(API)": "GR",
    "PERM(MD)": "PERM",
    "DTC(US/F)": "AC",
    "DTS(US/F)": "DTS",
    "DTS(US/FT)": "DTS",
    "DTC(US/FT)": "AC",
    "DTC": "AC",
    "VSH(V/V)": "SH",
    "SW(V/V)": "SW",
    "RM(OHMM)": "RM",
    "RM(OHM.M)": "RM",
    "RS(OHMM)": "RXO",
    "RS(OHM.M)": "RXO",
    "RD(OHMM)": "RT",
    "RD(OHM.M)": "RT",
    "CAL(IN)": "CAL",
    "PHIE(V/V)": "POR",
    "BIT(IN)": "BIT",
    "DEN(G/C3)": "DEN",
    "DEN(G/CM3)": "DEN",
    "DEN(G/CC)": "DEN",
    "SP(MV)": "SP",
    "SP(IN)": "SP",
    "CNCF(V/V)": "CNL",
    "CNCF(PU)": "CNL",
    "CNCF(%)": "CNL",
    "CNCF": "CNL",
    "RS": "RXO",
    "RS(OHM)": "RXO",
    "PHIE": "POR",
    "VSH": "SH",
    "VSH(S/F)": "SH",
}

# 曲线名 → 单位换算系数（用于将该曲线统一换算为目标单位后参与比较/计算）
RAW_DATA_FACTOR_MAP = {
    "DTC(US/F)": 3.28,
    "DTC(US/FT)": 3.28,
    "DTC": 3.28,
    "PHIE(V/V)": 100,
    "CAL(IN)": 2.54,
    "VSH(V/V)": 100,
    "SW(V/V)": 100,
}

# 标准曲线名 → 别名列表（按读取优先顺序，不区分大小写；首项即标准名本身）。
# 例：计算 RXO 曲线时先找 "RXO" 列，没有再按顺序找 "AT20"，再 "RLLS"……
STANDARD_CURVE_DICT: dict[str, list[str]] = {
    "GR": ["GR", "GR_EDTC", "ECGR_EDTC", "HGR", "GRGM", "ECGRTMG", "GR15"],
    "TH": ["TH", "THOR"],
    "K": ["K", "POTA"],
    "U": ["U", "URAN"],
    "CGR": ["CGR", "KTH", "GRKT"],
    "PE": ["PE", "PEF"],
    "SP": ["SP", "SP_S", "SPSADH", "HSP", "SPARDH"],
    "AC": ["AC", "DT24", "BHC", "DT", "DTCOMH", "DT24QI"],
    "DEN": ["DEN", "RHOB", "ZDEN"],
    "CNL": ["CNL", "CN", "NPHI", "CNC", "TNPH", "NPRL"],
    "RXO": ["RXO", "AT20", "RLLS", "RILM", "RS", "M2R2", "RT20", "MSFL",
            "RLL8", "RMSFL", "RSFL", "RFOC", "HT02", "AE20", "TAIT20", "LLS",
            "HLLS", "HL3S", "RL3S", "HR3S", "RLLSH", "DSLL", "ILM", "RMLS"],
    "RT": ["RT", "AT90", "RLLD", "RILD", "RD", "M2R9", "RT90", "HT09", "AE90",
           "LLD", "HL3D", "RL3D", "HR3D", "RLLDH", "DDLL", "RIPD", "ILD"],
    "QT": ["QT", "QC", "TG"],
    "ZT": ["ZT"],
    "DEVI": ["DEVI", "DEV", "DEV_CI", "DEVDPQH", "DEVODQH", "DEVODQI", "DEVXEQI",
             "SDEV", "DEVM", "INC", "BTLT", "DEVOD"],
    "AZIM": ["AZIM", "HAZ", "HAZ_CI", "HAZI", "DAZDPQH", "DAZODQH", "DAZODQI",
             "DAZXEQI", "DAZ", "AZM", "HAZIM", "BAZI", "DAZOD"],
    "CAL": ["CAL", "CAL_CML", "CAL_XY", "CAL_XYCAL", "CALI", "CALM", "CALA",
            "CAL_X", "CALX", "CALY", "CAL_D", "CAL4", "CALS", "CALC", "CALO"],
    "CBL": ["CBL", "CBL3", "CBL5"],
    "VDLW": ["VDLW", "VDL", "DENDQX", "WF1", "WF2", "WF5", "VDL5", "WVDL",
             "TFWV09", "TFWV01", "TFWV09N", "RVDL", "WAVE3", "WAVE5"],
    "CCL": ["CCL"],
    "ZS": ["ZS"],
    "SH": ["SH", "VSH"],
    "SAND": ["SAND", "VM3"],
    "CARB": ["CARB"],
    "LIME": ["LIME", "VM2"],
    "DOLO": ["DOLO", "VM1"],
    "VM4": ["VM4"],
    "ANHY": ["ANHY"],
    "CC": ["CC"],
    "ALOX": ["ALOX"],
    "FEOX": ["FEOX"],
    "XWY": ["XWY", "COSH", "CZNY"],
    "POR": ["POR", "PORT"],
    "PERM": ["PERM"],
    "SXO": ["SXO"],
    "SW": ["SW"],
    "SOG": ["SOG"],
    "VGAS": ["VGAS", "GC", "MGAS", "HGAS"],
    "HGAS": ["HGAS"],
    "ASH": ["ASH", "AAD", "ASHA", "MHFL"],
    "WFEN": ["WFEN", "MAD", "WP", "MWAT"],
    "HLOA": ["HLOA", "VAD", "MOIS", "MHFF", "VM"],
    "FIXC": ["FIXC", "FCAD", "MCLL", "FC"],
    "JZZ": ["JZZ", "VIT"],
    "DZZ": ["DZZ", "FUS"],
    "KWZ": ["KWZ"],
    "KZZ": ["KZZ", "SY"],
    "QF": ["QF", "QFBJ"],
    "QABJ": ["QABJ", "VA"],
    "FF1": ["FF1", "MTJG"],
    "LLL": ["LLL", "JJG"],
    "EEE": ["EEE", "YME_DYN", "EMOD"],
    "VVV": ["VVV", "PR_DYN", "POIS"],
    "BBI": ["BBI", "BRI"],
    "SHMINN": ["SHMINN", "SHMIN_PHS", "OMIN"],
    "SHMAXX": ["SHMAXX", "SHMAX_PHS", "OMAX"],
    "PPF": ["PPF", "PF"],
    "TVD": ["TVD"],
    "XE": ["XE"],
    "YN": ["YN"],
}